server:
  port: 8113
spring:
  profiles:
    active: local
  application:
    name: inside-service
  zipkin:
    base-url: http://localhost:11008

---
spring:
  profiles: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka/
